note
	description: "Comprehensive tests for SIMPLE_CHART"
	author: "Generated by simple_codegen"
	date: "2026-01-16"

class
	TEST_SIMPLE_CHART

inherit
	TEST_SET_BASE

feature -- Test: Creation

	test_make_creates_all_components
			-- Test that make initializes all components.
		local
			l_chart: SIMPLE_CHART
		do
			create l_chart.make
			assert ("data_loader_exists", l_chart.data_loader /= Void)
			assert ("bar_renderer_exists", l_chart.bar_renderer /= Void)
			assert ("table_renderer_exists", l_chart.table_renderer /= Void)
			assert ("no_data_initially", not l_chart.has_data)
			assert ("no_error_initially", l_chart.last_error = Void)
		end

feature -- Test: load_csv_string happy path

	test_load_csv_string_valid_data
			-- Test loading valid CSV string.
		local
			l_chart: SIMPLE_CHART
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value%NAlice,100%NBob,200")
			assert ("has_data", l_chart.has_data)
			assert ("no_error", l_chart.last_error = Void)
		end

	test_load_csv_string_single_row
			-- Test loading CSV with only header row.
		local
			l_chart: SIMPLE_CHART
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value")
			assert ("has_data", l_chart.has_data)
		end

	test_load_csv_string_many_columns
			-- Test loading CSV with many columns.
		local
			l_chart: SIMPLE_CHART
		do
			create l_chart.make
			l_chart.load_csv_string ("A,B,C,D,E,F,G,H%N1,2,3,4,5,6,7,8")
			assert ("has_data", l_chart.has_data)
			assert ("column_count", l_chart.data_loader.column_count = 8)
		end

feature -- Test: load_csv_string edge cases

	test_load_csv_string_whitespace_values
			-- Test CSV with whitespace in values.
		local
			l_chart: SIMPLE_CHART
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value%N  Alice  ,  100  ")
			assert ("has_data", l_chart.has_data)
		end

	test_load_csv_string_empty_cells
			-- Test CSV with empty cells.
		local
			l_chart: SIMPLE_CHART
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value,Extra%NAlice,,100%N,200,")
			assert ("has_data", l_chart.has_data)
		end

feature -- Test: render_bar_chart happy path

	test_render_bar_chart_valid
			-- Test rendering bar chart with valid data.
		local
			l_chart: SIMPLE_CHART
			l_result: STRING
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value%NAlice,100%NBob,200%NCharlie,150")
			l_result := l_chart.render_bar_chart (1, 2)
			assert ("result_not_empty", not l_result.is_empty)
			assert ("contains_alice", l_result.has_substring ("Alice"))
			assert ("contains_bob", l_result.has_substring ("Bob"))
			assert ("contains_bars", l_result.has_substring ("#"))
		end

	test_render_bar_chart_single_row
			-- Test bar chart with single data row.
		local
			l_chart: SIMPLE_CHART
			l_result: STRING
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value%NAlice,100")
			l_result := l_chart.render_bar_chart (1, 2)
			assert ("result_not_empty", not l_result.is_empty)
		end

feature -- Test: render_bar_chart edge cases

	test_render_bar_chart_zero_values
			-- Test bar chart when all values are zero.
		local
			l_chart: SIMPLE_CHART
			l_result: STRING
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value%NAlice,0%NBob,0")
			l_result := l_chart.render_bar_chart (1, 2)
			assert ("result_not_empty", not l_result.is_empty)
		end

	test_render_bar_chart_negative_values
			-- Test bar chart with negative values (treated as numeric).
		local
			l_chart: SIMPLE_CHART
			l_result: STRING
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Value%NAlice,-50%NBob,100")
			l_result := l_chart.render_bar_chart (1, 2)
			assert ("result_not_empty", not l_result.is_empty)
		end

feature -- Test: render_table

	test_render_table_valid
			-- Test rendering table with valid data.
		local
			l_chart: SIMPLE_CHART
			l_result: STRING
		do
			create l_chart.make
			l_chart.load_csv_string ("Name,Age,City%NAlice,30,NYC%NBob,25,LA")
			l_result := l_chart.render_table
			assert ("result_not_empty", not l_result.is_empty)
			assert ("has_border", l_result.has_substring ("+"))
			assert ("has_separator", l_result.has_substring ("|"))
			assert ("contains_headers", l_result.has_substring ("Name"))
			assert ("contains_data", l_result.has_substring ("Alice"))
		end

	test_render_table_wide_columns
			-- Test table with varying column widths.
		local
			l_chart: SIMPLE_CHART
			l_result: STRING
		do
			create l_chart.make
			l_chart.load_csv_string ("Short,VeryLongColumnHeader%NA,ThisIsAVeryLongValue")
			l_result := l_chart.render_table
			assert ("result_not_empty", not l_result.is_empty)
			assert ("contains_long_header", l_result.has_substring ("VeryLongColumnHeader"))
		end

end
